exports.seed = function(knex, Promise) {
  return knex('accounts').insert([
    {id:1, username:"meowser", type:"cat", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "Big Damage", profilepic:"http://www.catster.com/wp-content/uploads/2017/08/A-fluffy-cat-looking-funny-surprised-or-concerned.jpg", eatinghabits:"anything my human servants offer me as tribute", quirks:"sleeps in boxes, chases my own tail",age:14,bio:"I believe in nothing. I was born bloody and screaming. I will probably go out the same way"},
    {id:2, username:"professorCuddles", type:"dog", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "HotDog4U", profilepic:"https://static-cdn.jtvnw.net/jtv_user_pictures/dogdog-profile_image-5550ade194780dfc-300x300.jpeg", eatinghabits:"whenever its clever", quirks:"catches my own tail",age:3,bio:"I think that the Godather is an overrated movie."},
    {id:3, username:"fievel", type:"mouse", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "ThePatriotsSuck206", profilepic:"https://cdn.images.express.co.uk/img/dynamic/130/590x/secondary/A-mouse-1028634.jpg", eatinghabits:"whenever I can scrounge anything up", quirks:"can spot a mousetrap from a mile away",age:2,bio:"Time is a flat circle. I will do this again."},
    {id:4, username:"bigHiss", type:"snake", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "ImASlitherySnake", profilepic:"http://4.bp.blogspot.com/-k8-RnJZpYr8/UUYLLs_OfGI/AAAAAAAAAek/9y8KicbnvwU/s1600/2271832-snake.jpg", eatinghabits:"a mouse a week", quirks:"is essentially one giant knee",age:7,bio:"Ive never told anyone, but I hate the taste of mice. I prefer phad thai."},
    {id:5, username:"birdieNumNum", type:"bird", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "DiveBombin24-7", profilepic:"https://cdn.audubon.org/cdn/farfuture/xX2dO2IN71t0tfGOITDQ0HSLNOml6xiRu_z3MU6Xx5M/mtime:1486669862/sites/default/files/styles/engagement_card/public/sfw_apa_2013_28342_232388_briankushner_blue_jay_kk_high.jpg?itok=ttMfUhUu", eatinghabits:"whenever something is dropped", quirks:"doesnt have the confidence to be the point of the V",age:3,bio:"It is not accident. I am aiming for you."},
    {id:6, username:"alabaster St. James", type:"snake", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "SteadySlitherin'", profilepic:"http://desktop-backgrounds-org.s3.amazonaws.com/white-snake-animals_3.jpg", eatinghabits:"few and far between", quirks:"I've never left Washington State",age:3,bio:"I am terror that slithers in the night"},
    {id:7, username:"pickles", type:"dog", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "BigUpsToBrooklyn", profilepic:"https://thenypost.files.wordpress.com/2018/05/180516-woman-mauled-by-angry-wiener-dogs-feature.jpg?quality=90&strip=all&w=618&h=410&crop=1", eatinghabits:"better than your average canine", quirks:"I hate bones, weird right?",age:7,bio:"They say all dogs got to heaven. Obviously they haven't met me."},
    {id:8, username:"mortimer", type:"guinea pig", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "PackersFan425", profilepic:"https://s7d2.scene7.com/is/image/PetSmart/LCRefresh_Hero_ARFEAT-CaringForYourGuineaPig-20160818?$AR1601HI$", eatinghabits:"look at me, you tell me", quirks:"I sleep in wood shavings",age:4,bio:"I am not overweight, I'm mostly fur."},
    {id:9, username:"montgomery", type:"dog", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "SingleAndReadyPup", profilepic:"https://www.nationalgeographic.com/content/dam/animals/thumbs/rights-exempt/mammals/d/domestic-dog_thumb.ngsversion.1484159404151.adapt.1900.1.jpg", eatinghabits:"I eat whatever is in the bowl. It often isn't enough.", quirks:"Can't wag my tail to save my life. I'm self-conscious about it.",age:7,bio:"Being born beautiful isn't a crime"},
    {id:10, username:"dozer", type:"alligator", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "AncientBladeSlayer", profilepic:"https://www.genesispark.com/wp-content/uploads/2015/12/Alligator-Head.jpg", eatinghabits:"it better be alive. if it is, I am eatin' eat", quirks:"people think that I am a crocodile. those people are the worst", age:10,bio:"See you in a while..."},
    {id:11, username:"the Duke's Dear Freja", type:"spider", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "CrawlingInMySkin", profilepic:"https://www.amdro.com/-/media/images/amdro-na/us/blog/truth-about-tarantulas/tarantula-header.jpg", eatinghabits:"you don't want to know", quirks:"two of my legs are actually arms, guess which one?",age:14,bio:"No that wasn't me in the Lord Of The Rings..."},
    {id:12, username:"gus", type:"fish", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "SwimFan", profilepic:"https://images.unsplash.com/photo-1522720833375-9c27ffb02a5e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80", eatinghabits:"dem flakes, I love dem flakes. what are those anyway?", quirks:"Ironically I'm not a good swimmer",age:3,bio:"Why would I like Finding Nemo? My favorite movie is Full Metal Jacket"},
    {id:13, username:"sif", type:"wolf", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "Hatin'TheAbyssForLife253", profilepic:"https://static1.squarespace.com/static/55525830e4b0ac0977512301/t/55525f5ce4b0cdb7d2d0e977/1431461730441/IMG_0212a.jpg?format=1500w", eatinghabits:"if it is small and left unattended, it is mine", quirks:"Contrary to popular belief, I don't get hungry like the wolf...just hungry like any other animal",age:1,bio:"I am nothing. The king is dead. Long live the king."},
    {id:14, username:"scar", type:"lion", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "JungleKing", profilepic:"https://kids.nationalgeographic.com/content/dam/kids/photos/animals/Mammals/H-P/photoark-lion.ngsversion.1466004832449.png", eatinghabits:"I eat whatever I damn well please", quirks:"Fun Fact: I am inherently evil",age:7,bio:"I'm not my brother. Stop expecting me to live up to that"},
    {id:15, username:"sheldon", type:"turtle", password:"$2a$10$DpZ6lGglZwXC4IfEwoCT1OO7VfGCvOFJ1T9UeTt4lhi2U5LeqGdyK", displayname: "SlowAndSteady", profilepic:"http://www.tortoise.com/uploads/9/1/0/3/91034128/poppy-portrait_orig.jpg", eatinghabits:"plants, im a vegetarian", quirks:"I actually prefer sprinting to long-distance running.",age:42,bio:"I'm endangered. Talk that mess to me and you will be too."}
  ])
  .then(() => {
    return knex.raw("SELECT setval('accounts_id_seq', (SELECT MAX(id) FROM accounts));")
  })
};

